### ISSUE TITLE
Class 'Decoupled_Json_Content\Includes\Main' not found

### ISSUE THREAD

**Issue by nickyhajal** [infinum/decoupled-json-content#24]
This seems like a great plugin so trying to take it for a spin but getting the following error when I activate it:

```
Fatal error: Uncaught Error: Class 'Decoupled_Json_Content\Includes\Main' not found in /storage/ssd5/521/8004521/public_html/wp-content/plugins/decoupled-json-content-master/decoupled-json-content.php:76 Stack trace: #0 /storage/ssd5/521/8004521/public_html/wp-content/plugins/decoupled-json-content-master/decoupled-json-content.php(80): Decoupled_Json_Content\init_plugin() #1 /storage/ssd5/521/8004521/public_html/wp-admin/includes/plugin.php(1897): include('/storage/ssd5/5...') #2 /storage/ssd5/521/8004521/public_html/wp-admin/plugins.php(178): plugin_sandbox_scrape('decoupled-json-...') #3 {main} thrown in /storage/ssd5/521/8004521/public_html/wp-content/plugins/decoupled-json-content-master/decoupled-json-content.php on line 76
```

**Comment by shirokoweb** [comment]
@nickyhajal beside runing `composer -o dump-autoload` you'll have to make sure your zip content is named decoupled-json-content, not decoupled-json-content-master.
so it's /wp-content/plugins/decoupled-json-content otherwise, you'll get the same error.
